version: '3.3'
services:
  server:
    build: ./backend
    command: npm run start
    volumes:
      - ./backend:/usr/app/backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  client:
    build: .
    command: npm run client
    volumes:
      - .:/usr/app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
#    environment:
#      DATABASE_URL: postgres://todoapp@postgres/todos
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mgldefi'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mglFuture7@$'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'secret@12!'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - "./backend/src/db/new_mgldefi.sql:/docker-entrypoint-initdb.d/1.sql"
# Names our volume
volumes:
  my-db: